# Generated by Django 6.0.4 on 2026-04-25 17:38

import bookstudio.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstudio', '0002_alter_book_updated_at_alter_bookedition_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPatternSet',
            fields=[
                ('id', models.CharField(default=bookstudio.utils.uuid_key, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('palette', models.JSONField(blank=True, default=dict)),
                ('target_layout', models.CharField(default='PPTX_WIDE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DesignPattern',
            fields=[
                ('id', models.CharField(default=bookstudio.utils.uuid_key, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('TITLE', 'Title Slide'), ('SECTION', 'Section Divider'), ('CONTENT', 'Content'), ('CONTENT_2COL', 'Two Column Content'), ('IMAGE', 'Image Focus'), ('IMG_TXT', 'Image + Text'), ('DATA', 'Data / Key Figures'), ('COMPARISON', 'Comparison'), ('QUOTE', 'Quote / Highlight'), ('CLOSING', 'Closing / CTA'), ('BLANK', 'Blank Canvas')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('target_layout', models.CharField(choices=[], default='PPTX_WIDE', max_length=20)),
                ('page_background_type', models.CharField(default='CLR', max_length=10)),
                ('page_background_color', models.CharField(default='#ffffff', max_length=30)),
                ('page_opacity', models.FloatField(default=1.0)),
                ('palette', models.JSONField(blank=True, default=dict)),
                ('typography', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('LEGACY', 'Extracted from Legacy'), ('CURATED', 'Curated'), ('AI_GEN', 'AI Generated')], default='CURATED', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_patterns', to='bookstudio.page')),
            ],
            options={
                'ordering': ['category', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='DesignPatternSetMembership',
            fields=[
                ('id', models.CharField(default=bookstudio.utils.uuid_key, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_memberships', to='bookstudio.designpattern')),
                ('pattern_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='bookstudio.designpatternset')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='DesignPatternSlot',
            fields=[
                ('id', models.CharField(default=bookstudio.utils.uuid_key, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('title', 'Title'), ('subtitle', 'Subtitle'), ('body', 'Body Text'), ('image', 'Image'), ('accent', 'Accent / Decoration'), ('icon', 'Icon / Shape'), ('caption', 'Caption'), ('number', 'Key Number / Stat')], max_length=20)),
                ('media_type', models.CharField(default='TXT', max_length=20)),
                ('left_pct', models.FloatField()),
                ('top_pct', models.FloatField()),
                ('width_pct', models.FloatField()),
                ('height_pct', models.FloatField()),
                ('style', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bookstudio.designpattern')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='designpattern',
            index=models.Index(fields=['category', 'target_layout', 'is_active'], name='bookstudio__categor_9dd446_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='designpatternsetmembership',
            unique_together={('pattern_set', 'pattern')},
        ),
    ]
