# Generated by Django 6.0.4 on 2026-04-25 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstudio', '0003_design_pattern_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpattern',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='designpatternset',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
