# Generated by Django 6.0.4 on 2026-04-25 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstudio', '0004_design_pattern_fix_auto_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpattern',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
