# Generated by Django 6.0.4 on 2026-04-25 23:43

import bookstudio.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstudio', '0005_design_pattern_fix_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISession',
            fields=[
                ('id', models.CharField(default=bookstudio.utils.uuid_key, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('REVIEW', 'Awaiting Review'), ('APPROVED', 'Approved'), ('GENERATING', 'Generating'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('plan', models.JSONField(blank=True, null=True)),
                ('total_pages', models.PositiveSmallIntegerField(default=0)),
                ('completed_pages', models.PositiveSmallIntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('total_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_output_tokens', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='bookstudio.book')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='bookstudio.bookedition')),
                ('pattern_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstudio.designpatternset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookstudio_ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='bookstudio__user_id_dc2328_idx'), models.Index(fields=['book', '-created_at'], name='bookstudio__book_id_b3e46b_idx')],
            },
        ),
    ]
