# Generated by Django 6.0.4 on 2026-04-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstudio', '0006_ai_session_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpattern',
            name='target_layout',
            field=models.CharField(choices=[('BOOK', 'Book (A4 Portrait)'), ('MBOOK', 'Mini Book'), ('CD', 'CD / Square'), ('CARD', 'Card'), ('CINEMA', 'Cinema'), ('BANNER', 'Banner'), ('PPTX_WIDE', 'PPTX Wide 16:9'), ('PPTX_STD', 'PPTX Standard 4:3'), ('PPTX_WP', 'PPTX Wide Portrait 9:16'), ('PPTX_SP', 'PPTX Standard Portrait 3:4'), ('A4_LAND', 'A4 Landscape'), ('CUSTOM', 'Custom')], default='PPTX_WIDE', max_length=20),
        ),
        migrations.AlterField(
            model_name='designpatternset',
            name='target_layout',
            field=models.CharField(choices=[('BOOK', 'Book (A4 Portrait)'), ('MBOOK', 'Mini Book'), ('CD', 'CD / Square'), ('CARD', 'Card'), ('CINEMA', 'Cinema'), ('BANNER', 'Banner'), ('PPTX_WIDE', 'PPTX Wide 16:9'), ('PPTX_STD', 'PPTX Standard 4:3'), ('PPTX_WP', 'PPTX Wide Portrait 9:16'), ('PPTX_SP', 'PPTX Standard Portrait 3:4'), ('A4_LAND', 'A4 Landscape'), ('CUSTOM', 'Custom')], default='PPTX_WIDE', max_length=20),
        ),
    ]
