# Generated by Django 6.0.4 on 2026-05-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstudio', '0009_fix_tenant_fk_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpattern',
            name='category',
            field=models.CharField(choices=[('TITLE', 'Title Slide'), ('SECTION', 'Section Divider'), ('CONTENT', 'Content'), ('CONTENT_2COL', 'Two Column Content'), ('IMAGE', 'Image Focus'), ('IMG_TXT', 'Image + Text'), ('DATA', 'Data / Key Figures'), ('COMPARISON', 'Comparison'), ('QUOTE', 'Quote / Highlight'), ('CLOSING', 'Closing / CTA'), ('BLANK', 'Blank Canvas'), ('STATS', 'KPI / Statistics'), ('THREE_COL', 'Three Column'), ('GRID_CARDS', 'Card Grid'), ('FLOW', 'Process Flow'), ('TIMELINE', 'Timeline / Roadmap'), ('CHART', 'Chart Focus'), ('PRICING', 'Pricing Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='designpatternslot',
            name='role',
            field=models.CharField(choices=[('title', 'Title'), ('subtitle', 'Subtitle'), ('body', 'Body Text'), ('image', 'Image'), ('accent', 'Accent / Decoration'), ('icon', 'Icon / Shape'), ('caption', 'Caption'), ('number', 'Key Number / Stat'), ('card', 'Card Container'), ('stat_value', 'Stat Value'), ('stat_label', 'Stat Label'), ('badge', 'Status Badge'), ('icon_box', 'Icon Box'), ('header', 'Header Bar'), ('footer', 'Footer Bar'), ('summary', 'Summary Bar'), ('flow_node', 'Flow Node'), ('chart_area', 'Chart Area'), ('progress', 'Progress Bar')], max_length=20),
        ),
    ]
